# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v1.json
language: "en-US"
version: 1

exclude:
  paths:
    - ".github/workflows/"
    - ".github/workflows/*.yml"
    - ".github/workflows/*.yaml"
  patterns:
    - "z0al/dependent-issues"
    - "actions/checkout@v"
    - "coursier/cache-action@v"
    - "actions/setup-java@v"
    - "actions/add-to-project@v"
    - "actions/setup-python@v"
