\echo Creating users
\ir database/users.ddl

\echo Creating 'pgarray' schema content
\ir database/pgarray/_.ddl
\ir database/pgarray/is_unique.sql

\echo Creating 'pgutils' schema content
\ir database/pgutils/_.ddl
\ir database/pgutils/_restore_constraints.sql
\ir database/pgutils/_suspend_constraints.sql
\ir database/pgutils/_trg_suspended_constraints_in_transaction_empty_check.sql
\ir database/pgutils/active_mutexes.ddl
\ir database/pgutils/can_role_alter_table.sql
\ir database/pgutils/can_role_modify_table_data.sql
\ir database/pgutils/suspend_constraints.sql
\ir database/pgutils/suspend_constraints_by_name.sql
\ir database/pgutils/suspended_constraints_in_transaction.ddl
\ir database/pgutils/suspended_constraints_persistently.ddl
\ir database/pgutils/global_id.sql
\ir database/pgutils/list_constraints.sql
\ir database/pgutils/lock_mutex.sql
\ir database/pgutils/log_to_console.sql
\ir database/pgutils/restore_all_constraints.sql
\ir database/pgutils/restore_constraints.sql

\echo All done
