#
# Copyright 2026 David Benedeki, All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Test

on:
  pull_request:
    branches:
      - '**'
    types: [ opened, synchronize, reopened ]

env:
  postgres-password: "postgres"
  tester-password: "ChangeMe!"

jobs:
  test-database-and-server:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: ${{ env.postgres-password }}
          POSTGRES_DB: pgutils_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 1
          persist-credentials: false
      - uses: coursier/cache-action@bebeeb0e6f48ebad66d3783946588ecf43114433

      # Install Java 8 (AdoptOpenJDK)
      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install SDKMAN
        run: curl -s "https://get.sdkman.io" | bash

      - name: Install Scala + sbt
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install scala 2.12.18
          sdk install sbt 1.10.0

      - name: Prepare testing database
        env:
          PGPASSWORD:  ${{ env.postgres-password }}
        run: |
          psql -h 127.0.0.1 -U postgres -d pgutils_db -v ON_ERROR_STOP=1 -f install.psql
          psql -h 127.0.0.1 -U postgres -d pgutils_db -v ON_ERROR_STOP=1 -f testing_install.psql
          psql -h 127.0.0.1 -U postgres -d pgutils_db -v ON_ERROR_STOP=1 -c "GRANT CONNECT ON DATABASE pgutils_db TO pgutils_tester;"

      - name: Run tests
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sbt test
